### PR TITLE
Fixes #231 :- error clear

### LINKED ISSUE #231: Search service crashes on Clicking 'Show more'
screen shot 2017-01-22 at 2 00 33 pm

This error is making Search service to crash. Reason for this is that sometimes apiresponseaggregations is returned as null  on Clicking on "Show more" for new feeds and statistics in info-box is set to undefined which gives an error.

### PR DESCRIPTION
**Pull request by Achint08**
Fixes #231 .
Previously there was an error message because new API Response Aggregations sometimes returned null when there were no new tweet feeds on clicking "Show more"  due to which search service crashed. The error is shown below :-

screen shot 2017-01-22 at 2 00 33 pm

You can come across the error by searching for some queries(Keep a check on console meanwhile) on loklak.net .Now click on "Show more" for new tweets. Try this for 2-3 queries. You will come across this error sometimes.
 
What I did is that in case api response  aggregation is returned null , I have set the previous aggregation to the new aggregation. Now the variable statistics in the info box component will not be undefined anytime.
 I also changed boolean variable conditional operation from 30 to 20. The reason being previously I changed number of requested tweets(records) from 30 to 20.
gh-pages :- https://achint08.github.io/loklak_search/
Kindly review and correct me. :)

### CODE REVIEW

File: src/app/reducers/api-response.ts [hunk 1]
```diff
@@ -87,12 +87,18 @@ export function reducer(state: State = initialState, action: api.Actions | pagin
 			let hashtags = Array.from(new Set(tagStrings)).map(tag => {
 					return { tag, count: tagStrings.filter(y => y === tag).length };
 			});
+			let oldapiaggregations = state.aggregations;
+			let newapiaggregations = apiResponse.aggregations;
+			if(newapiaggregations === null)
```
Comment (yukiisbored) [inline src/app/reducers/api-response.ts]: Add space between the `if` syntax and the parenthesis and Please make the bracket on the same line as the if statement.
Basically, Make your code consistent with the project.

**Comment by yukiisbored** [comment]
The commit message is unclear, I'm not quite sure what's the change. Can you please improve the commit message and explain what the changes you did. If you want to know what a good commit message looks like See coala.io/commit.

File: src/app/reducers/api-response.ts (hunk 1 above)
Comment (Achint08) [inline src/app/reducers/api-response.ts]: Done. :)

**Comment by Achint08** [comment]
@yukiisbored I will surely look ahead and improve myself and make a good commit message from next time.

File: src/app/reducers/api-response.ts [hunk 2]
```diff
@@ -87,12 +87,17 @@ export function reducer(state: State = initialState, action: api.Actions | pagin
...
+			if (newapiaggregations === null) {
+				newapiaggregations = oldapiaggregations;
+			}
 
 			return Object.assign({}, state, {
 				pages:	[...state.pages, apiResponse],
 				entities: [...state.entities, ...apiResponse.statuses],
 				hashtags: [...hashtags],
-				aggregations: apiResponse.aggregations,
+				aggregations: newapiaggregations,
```
Comment (hemantjadon) [inline src/app/reducers/api-response.ts]: Directly set `apiResponse.aggregations | state.aggregations`

Comment (Achint08) [inline src/app/reducers/api-response.ts]: I can use this operation only when right side is of type number , any or enum. Any idea?

Comment (hemantjadon) [inline src/app/reducers/api-response.ts]: Ohh sorry my mistake, It should be `apiResponse.aggregations || state.aggregation`, single `|` is bitwise operator(applicable on type numbers) thus the error.

Comment (Achint08) [inline src/app/reducers/api-response.ts]: @hemantjadon Done. :)
